{{- if .Values.externalIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "schema-registry.fullname" . }}-external
  labels:
    app: {{ template "schema-registry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.externalIngress.labels }}
{{ toYaml .Values.externalIngress.labels | indent 4 }}
{{- end }}
{{- if .Values.externalIngress.annotations }}
  annotations:
{{ toYaml .Values.externalIngress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.externalIngress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "schema-registry.fullname" . }}
                port:
                  number: {{ .Values.servicePort }}
{{- if .Values.externalIngress.tls.enabled }}
  tls:
    - secretName: {{ .Values.externalIngress.tls.secretName }}
      hosts:
        - {{ .Values.externalIngress.hostname }}
{{- end -}}
{{ end -}}
